# Generated by Django 3.0.7 on 2021-03-09 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20210302_2352'),
        ('content', '0008_auto_20210302_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/contents/%Y/%m/%d/', verbose_name='Image')),
                ('source', models.TextField(verbose_name='Source')),
                ('license', models.CharField(blank=True, max_length=200, verbose_name='License')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ImageAttachments', to='base.Content', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Image Attachment',
                'verbose_name_plural': 'Image Attachments',
            },
        ),
    ]
